(* 6  Z characters			ISO/IEC 13568:2002(E) *)

(* 6.2 Formal definition of Z characters *)

(* Copyright notice *)

(* The reproduction of this clause is permitted on the understanding that *)
(* this material is public domain, and on the condition that this *)
(* International Standard is referenced as the source document.  With the *)
(* exception of clauses 6.2, 7.2, 8.2, 11 and annex B, all other parts of *)
(* the text are subject to the usual copyright rules stated on page ii of *)
(* this International Standard. *)

ZCHAR = DIGIT | LETTER | SPECIAL | SYMBOL ;

DIGIT = DECIMAL
	| ? other UCS chars with Number property but Number, Decimal Digit (as supported) ?
	;

DECIMAL = '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8'
	| '9'
	| ? any other UCS characters with Number, Decimal Digit property (as supported) ?
	;

LETTER = LATIN | GREEK | OTHERLETTER
	| ? any characters of the mathematical toolkit with letter property (as supported) ?
	| ? any other UCS characters with letter property (as supported) ?
	;

LATIN = 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I '
	| 'J ' | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R'
	| 'S' | 'T' | 'U' | 'V' | 'W' | 'X' | 'Y ' | 'Z'
	| 'a' | 'b' | 'c' | 'd' | 'e' | 'f ' | 'g' | 'h' | 'i'
	| 'j ' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r'
	| 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z'
	;

GREEK =
'Δ' (* \u0394 *)
	| 'Ξ' (* \u039E *)
	| 'θ' (* \u03B8 *)
	| 'λ' (* \u03BB *)
	| 'μ' (* \u03BC *)
	;

OTHERLETTER = '𝔸'  (* double-struck cap A:  \u0001 D538 *)
	| 'ℕ' (* \u2115 *)
	| 'ℙ'  (* \u2119 *)
	;

SPECIAL = STROKECHAR | WORDGLUE | BRACKET | BOXCHAR | NLCHAR | SPACE ;

STROKECHAR = 'ʹ'  (* \u02B9 MODIFIER LETTER PRIME *)
	| '!' | '?' ;

WORDGLUE = '↗' (* \u2197 NORTH EAST ARROW *)
	| '↙'  (* \u2199 SOUTH WEST ARROW *)
	| '↘'  (* \u2198 SOUTH EAST ARROW *)
	| '↖'  (* \u2196 NORTH WEST ARROW *)
	| '_ ' (* \u005F LOW LINE *)
	;

BRACKET = '(' | ')'
	| '[' | ']'
	| '{' | '}'
	| '⦉' | '⦊'	(* \u2989/298A Z NOTATION LEFT/RIGHT BINDING BRACKET *)
	| '《' | '》' (* \u300A/300B LEFT/RIGHT DOUBLE ANGLE BRACKET *)
	;

BOXCHAR = ZEDCHAR | AXCHAR | SCHCHAR | GENCHAR | ENDCHAR ;

SYMBOL = '|'
	| '&'
	| '⊢'	(* \u22A2 RIGHT TACK *)
	| '∧'	(* \u2227 LOGICAL AND *)
	| '∨'	(* \u2228 LOGICAL OR  *)
	| '⇒'	(* \u21D2 RIGHTWARDS DOUBLE ARROW *)
	| '⇔'	(* \u21D4 LEFT RIGHT DOUBLE ARROW *)
	| '¬'	(* \u00AC NOT SIGN *)
	| '∀'	(* \u2200 FOR ALL *)
	| '∃'	(* \u2203 THERE EXISTS *)
	| '×'	(* \u00D7 MULTIPLICATION SIGN *)
	| '/'	(* SOLIDUS *)
	| '='	(* EQUALS SIGN *)
	| '∈'	(* \u2208 ELEMENT OF *)
	| ':'	(* COLON *)
	| '; '	(* SEMICOLON *)
	| ','	(* COMMA *)
	| '.'	(* FULL STOP *)
	| '⦁'	(* \u2981 Z NOTATION SPOT *)
	| '⧹'	(* \u29F9 BIG REVERSE SOLIDUS *)
	| '⨡'	(* \u2A21 Z NOTATION SCHEMA PROJECTION *)
	| '⨟'	(* \u2A21 Z NOTATION SCHEMA COMPOSITION *)
	| '⨠'	(* \u2A20 Z NOTATION SCHEMA PIPING *)
	| '+'	(* \u002B PLUS SIGN *)
	| ? any characters of the mathematical toolkit with neither letter or
number property (as supported) ?
	| ? any other UCS characters with neither letter or
number property and that are not in SPECIAL(as supported) ?
	| MATH
	;

(* c ISO/IEC 2002|All rights reserved				19 *)

(* 6.4.6 Mathematical toolkit characters *)

MATH = SET-TK | RELATION-TK | FUNCTION-TK | NUMBER-TK | SEQUENCE-TK ;

SET-TK = '↔'  (* \u0000 2194 LEFT RIGHT ARROW *)
	| '→'  (* \u2192 RIGHTWARDS ARROW *)
	| '≠'  (* \u2260 NOT EQUAL TO *)
	| '∈'  (* \u2209 NOT AN ELEMENT OF *)
	| '∅'  (* \u2205 EMPTY SET *)
	| '⊆'  (* \u2286 SUBSET OF OR EQUAL TO *)
	| '⊂'  (* \u2282 SUBSET OF *)
	| '∪'  (* \u222A UNION *)
	| '∩'  (* \u2229 INTERSECTION *)
	| '\'  (* \u005C REVERSE SOLIDUS *)
	| '⊖'  (* \u2296 CIRCLED MINUS *)
	| '⋃'  (* \u22C3 N-ARY UNION *)
	| '⋃'  (* \u22C2 N-ARY INTERSECTION *)
	| '𝔽' (* \uD53D MATHEMATICAL DOUBLE-STRUCK CAPITAL F *)
	;

RELATION-TK = '↦'   (* \u21A6  RIGHTWARDS ARROW FROM BAR *)
	| '⨾'			(* \u2A3E Z NOTATION RELATIONAL COMPOSITION *)
	| '∘'			(* \u2218 RING OPERATOR *)
	| '▹'			(* \u25C1 WHITE LEFT-POINTING TRIANGLE *)
	| '◃'			(* \u25B7 WHITE RIGHT-POINTING TRIANGLE *)
	| '⩤'			(* \u2A64 Z NOTATION DOMAIN ANTIRESTRICTION *)
	| '⩥'			(* \u2A65 Z NOTATION RANGE ANTIRESTRICTION *)
	| '∼'			(* \u223C TILDE OPERATOR *)
	| '⦇'			(* \u2987 Z NOTATION LEFT IMAGE BRACKET *)
	| '⦈'			(* \u2988 Z NOTATION RIGHT IMAGE BRACKET *)
	| '⊕'			(* \u2295 CIRCLED PLUS *)
	;

FUNCTION-TK = '⇸'	(* \u21F8 RIGHTWARDS ARROW WITH VERTICAL STROKE *)
	| '⤔' (* \u2914 RIGHTWARDS ARROW WITH TAIL WITH VERTICAL STROKE *)
	| '↣' (* \u21A3 RIGHTWARDS ARROW WITH TAIL *)
	| '⤀' (* \u2900 RIGHTWARDS TWO-HEADED ARROW WITH VERTICAL STROKE *)
	| '↠' (* \u21A0 RIGHTWARDS TWO-HEADED ARROW *)
	| '⤖' (* \u2916 RIGHTWARDS TWO-HEADED ARROW WITH TAIL *)
	| '⇻' (* \u21FB RIGHTWARDS ARROW WITH DOUBLE VERTICAL STROKE *)
	| '⤕' (* \u2915 RIGHTWARDS ARROW WITH TAIL WITH DOUBLE VERTICAL STROKE *)
	;

NUMBER-TK = 'ℤ' (* \u2124 DOUBLE-STRUCK CAPITAL Z *)
	| '-'		(* \u002D HYPHEN-MINUS *)
	| '−'		(* \u2212 MINUS SIGN *)
	| '≤'		(* \u2264 LESS-THAN OR EQUAL TO *)
	| '<'		(* \u003C LESS-THAN SIGN *)
	| '≥'		(* \u2265 GREATER-THAN OR EQUAL TO *)
	| '>'		(* \u003E GREATER-THAN SIGN *)
	| '*'		(* \u002A ASTERISK *)
	;

SEQUENCE-TK = '#' (* \u0023 NUMBER SIGN *)
	| '〈'		  (* \u3008 LEFT ANGLE BRACKET *)
	| '〉'		  (* \u3009 RIGHT ANGLE BRACKET *)
	| '⁀'		  (* \u2040 CHARACTER TIE *)
	| '↿'		  (* \u21BF UPWARDS HARPOON WITH BARB LEFTWARDS *)
	| '↾'		  (* \u21BE UPWARDS HARPOON WITH BARB RIGHTWARDS *)
	;
